### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [ikelos/gentoo-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you pick one

**Comment by ikelos** [comment]
It's really just a clone of the one already in oh-my-zsh, so I guess it's MIT licensed?

Here's the screenshot I intend to use...

![Screenshot](https://user-images.githubusercontent.com/1477845/54884174-ba8d5a00-4e65-11e9-8f8e-a0e7ee1c79bf.png)

**Comment by ikelos** [comment]
Hopefully this has been suitably resolved, so I'm going to mark it as closed.  Feel free to reopen it if you feel there's more I need to do...

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/676, thanks
